"""Build RGB565 crop thumbnails for the ST7789 preview sketch."""

import csv
from pathlib import Path

from PIL import Image, ImageOps


DATA_DIR = Path(__file__).parent
PHOTOS_DIR = DATA_DIR / "crop_photos_v1"
OUTPUT = DATA_DIR.parent / "firmware" / "SmartSoilCropPhotoPreview" / "CropPhotoAssets.h"
WIDTH = 120
HEIGHT = 90
BACKGROUND = (14, 22, 20)


def rgb565(rgb):
    red, green, blue = rgb
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def thumbnail(path):
    with Image.open(path) as source:
        source = ImageOps.exif_transpose(source).convert("RGB")
        source.thumbnail((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
        canvas = Image.new("RGB", (WIDTH, HEIGHT), BACKGROUND)
        canvas.paste(source, ((WIDTH - source.width) // 2, (HEIGHT - source.height) // 2))
        return [rgb565(pixel) for pixel in canvas.get_flattened_data()]


def main():
    with (PHOTOS_DIR / "manifest.csv").open(newline="", encoding="utf-8") as handle:
        photos = {int(row["id"]): row for row in csv.DictReader(handle)}
    with (DATA_DIR / "crop_reference_v1.csv").open(newline="", encoding="utf-8") as handle:
        crops = list(csv.DictReader(handle))

    lines = [
        "// Generated by data/build_tft_crop_photos.py; do not edit manually.",
        "#pragma once",
        "#include <Arduino.h>",
        f"constexpr uint16_t CROP_PHOTO_WIDTH = {WIDTH};",
        f"constexpr uint16_t CROP_PHOTO_HEIGHT = {HEIGHT};",
        "struct CropPhotoMeta {",
        "  const char *name;",
        "  const uint16_t *pixels;",
        "  uint8_t vwc_min, vwc_max, temp_min, temp_max;",
        "  float ph_min, ph_max;",
        "};",
    ]

    image_count = 0
    for crop in crops:
        crop_id = int(crop["id"])
        photo = photos[crop_id]
        if crop["crop_name_en"] != photo["crop_name_en"]:
            raise ValueError(f"Crop name mismatch at ID {crop_id}")
        if not photo["photo_file"]:
            continue
        pixels = thumbnail(PHOTOS_DIR / photo["photo_file"])
        symbol = f"CROP_PHOTO_{crop_id:02d}"
        lines.append(f"static const uint16_t {symbol}[{WIDTH * HEIGHT}] PROGMEM = {{")
        for index in range(0, len(pixels), 12):
            lines.append("  " + ", ".join(f"0x{value:04X}" for value in pixels[index:index + 12]) + ",")
        lines.append("};")
        image_count += 1

    lines.append("static const CropPhotoMeta CROP_PHOTOS[] = {")
    for crop in crops:
        crop_id = int(crop["id"])
        symbol = f"CROP_PHOTO_{crop_id:02d}" if photos[crop_id]["photo_file"] else "nullptr"
        lines.append(
            f'  {{"{crop["crop_name_en"]}", {symbol}, '
            f'{crop["soil_vwc_min_pct"]}, {crop["soil_vwc_max_pct"]}, '
            f'{crop["soil_temp_min_c"]}, {crop["soil_temp_max_c"]}, '
            f'{crop["soil_ph_min"]}f, {crop["soil_ph_max"]}f}},'
        )
    lines.extend([
        "};",
        "constexpr uint8_t CROP_PHOTO_COUNT = sizeof(CROP_PHOTOS) / sizeof(CROP_PHOTOS[0]);",
        "",
    ])

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="ascii")
    print(f"Built {image_count} thumbnails for {len(crops)} crops: {OUTPUT}")
    print(f"RGB565 pixel payload: {image_count * WIDTH * HEIGHT * 2} bytes")


if __name__ == "__main__":
    main()
